version: '3'
services:
  app:
    build: .
    env_file:
      - .env.development 
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:13
    env_file:
      - .env.development  # Carregar variáveis de ambiente do arquivo .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
