version: '3'
services:
  app:
    build: .
    env_file:
      - .env.development 
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: >
      sh -c "sleep 10 &&
             npx prisma migrate deploy --schema /app/prisma/schema.prisma &&
             npx prisma migrate deploy --schema /app/src/biomedsandra-api/course/prisma/schema.prisma &&
             npx prisma generate --schema /app/prisma/schema.prisma &&
             npx prisma generate --schema /app/src/biomedsandra-api/course/prisma/schema.prisma &&
             npm run dev"

  db:
    image: postgres:13
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
