version: '3.8'
services:
  app:
    build: .
    container_name: nestjs-app
    env_file:
      - .env.development 
    environment:
      - NODE_ENV=${NODE_ENV:-development} # Define NODE_ENV, mas permite sobrescrever
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
      #- /app/node_modules
    depends_on:
      - db
    command: >
      sh -c "sleep 10 &&
             npx prisma migrate deploy --schema /app/prisma/schema.prisma &&
             npx prisma generate --schema /app/prisma/schema.prisma &&
             npm run start:debug" # No desenvolvimento, usamos o debug

  db:
    image: postgres:13
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
