# fly.toml app configuration file generated for devtechw7-backend-small-violet-5481 on 2024-10-09T21:58:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devtechw7-backend-small-violet-5481'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 5432
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 5432
    handlers = ["pg"]

  [[mounts]]
    source = "postgres_data"   
    destination = "/var/lib/postgresql/data"

