name: Build and Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env.production
        run: echo "${{ secrets.PRODUCTION_ENV_FILE }}" > .env.production

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devtechw7-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/devtechw7-backend:latest

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "FLYCTL_INSTALL=/home/runner/.fly" >> $GITHUB_ENV
          echo "PATH=/home/runner/.fly/bin:$PATH" >> $GITHUB_ENV

      - name: Export updated PATH
        run: source $GITHUB_ENV

      - name: Log in to Fly.io
        run: flyctl auth token ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: flyctl deploy